"""Exact weighted equitable partitions for sparse row matrices.

Rows use the same representation as :mod:`src.automaton`: a finite sequence
of dictionaries, where ``rows[i][j]`` is the (possibly repeated) transition
weight from state ``i`` to state ``j``.  The weights are exact nonnegative
``int`` or :class:`fractions.Fraction` values.

The refinement routine is a weighted, directed colour refinement.  It starts
with one block and repeatedly splits a block according to the sparse vector
of total weights sent to every current block.  Thus the returned partition is
deterministic, stable, and the coarsest stable refinement generated by these
signatures.  No dense state-by-state matrix is constructed.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from fractions import Fraction
from typing import TypeAlias


Weight: TypeAlias = int | Fraction
Row: TypeAlias = dict[int, Weight]

__all__ = [
    "equitable_partition",
    "quotient",
    "verify_equitable",
    "lift_vector",
]


def _materialize(value: Iterable[object], name: str) -> list[object]:
    """Materialize an input sequence while rejecting text-like values."""

    if isinstance(value, (str, bytes, bytearray)):
        raise TypeError(f"{name} must be an iterable of states, not text")
    try:
        return list(value)
    except TypeError as exc:
        raise TypeError(f"{name} must be an iterable") from exc


def _validate_weight(value: object, name: str) -> Weight:
    """Return an exact nonnegative coefficient or raise a useful error."""

    # ``bool`` is an ``int`` subclass, so exact type checks are intentional.
    if type(value) is int:
        if value < 0:
            raise ValueError(f"{name} must be nonnegative")
        return value
    if type(value) is Fraction:
        if value < 0:
            raise ValueError(f"{name} must be nonnegative")
        return value
    raise TypeError(f"{name} must be an int or Fraction, not {type(value).__name__}")


def _validate_rows(rows: Iterable[Mapping[object, object]]) -> list[Mapping[object, object]]:
    """Validate sparse rows and return them as a materialized list.

    Destinations are checked against the number of rows, which also prevents
    accidental construction of a quotient with an out-of-range state index.
    """

    row_list = _materialize(rows, "rows")
    state_count = len(row_list)
    for source, row in enumerate(row_list):
        if not isinstance(row, Mapping):
            raise TypeError(f"rows[{source}] must be a mapping")
        for destination, weight in row.items():
            if type(destination) is not int:
                raise TypeError(
                    f"rows[{source}] destination must be an int, "
                    f"not {type(destination).__name__}"
                )
            if destination < 0 or destination >= state_count:
                raise ValueError(
                    f"rows[{source}] destination {destination} is outside "
                    f"0..{state_count - 1}"
                )
            _validate_weight(weight, f"rows[{source}][{destination}]")
    return row_list


def _validate_mapping(mapping: Iterable[object], state_count: int) -> list[int]:
    """Validate a canonical state-to-block mapping.

    Block labels are required to be exactly ``0, ..., k-1``.  This removes an
    otherwise needless label-normalization ambiguity from quotient rows.
    """

    result = _materialize(mapping, "mapping")
    if len(result) != state_count:
        raise ValueError(
            f"mapping has length {len(result)} but rows have {state_count} states"
        )
    labels: list[int] = []
    for state, block in enumerate(result):
        if type(block) is not int:
            raise TypeError(
                f"mapping[{state}] must be an int, not {type(block).__name__}"
            )
        if block < 0:
            raise ValueError(f"mapping[{state}] must be nonnegative")
        labels.append(block)
    present = sorted(set(labels))
    if present != list(range(len(present))):
        raise ValueError("mapping block labels must be contiguous from zero")
    return labels


def _signature(row: Mapping[int, Weight], mapping: list[int]) -> tuple[tuple[int, Weight], ...]:
    """Sparse weighted signature of one row against the current partition."""

    totals: dict[int, Weight] = {}
    for destination, weight in row.items():
        if weight == 0:
            continue
        block = mapping[destination]
        totals[block] = totals.get(block, 0) + weight
    # A missing block has total zero; omitting it keeps memory proportional to
    # the number of nonzero transitions rather than to the number of states.
    return tuple(sorted(totals.items()))


def _aggregate(row: Mapping[int, Weight], mapping: list[int]) -> dict[int, Weight]:
    """Aggregate one row by destination block in deterministic key order."""

    totals: dict[int, Weight] = {}
    for destination, weight in row.items():
        if weight == 0:
            continue
        block = mapping[destination]
        totals[block] = totals.get(block, 0) + weight
    return dict(sorted(totals.items()))


def equitable_partition(rows: Iterable[Mapping[object, object]]) -> list[int]:
    """Return the stable weighted equitable partition of ``rows``.

    The first partition has one block.  In each round, states in an existing
    block are grouped by the sparse signature of their total outgoing weight
    into each existing block.  Existing block order is retained; signatures
    inside a block are sorted lexicographically.  This makes both the result
    and its block labels deterministic for a fixed row representation.

    The running memory is ``O(n + E)`` for ``n`` states and ``E`` nonzero row
    entries, apart from the sparse signatures held during one refinement
    round.  In particular, no ``n`` by ``n`` matrix is allocated.
    """

    row_list = _validate_rows(rows)
    state_count = len(row_list)
    if state_count == 0:
        return []

    partition = [0] * state_count
    while True:
        block_count = max(partition) + 1
        states_by_block: list[list[int]] = [[] for _ in range(block_count)]
        for state, block in enumerate(partition):
            states_by_block[block].append(state)

        refined = [-1] * state_count
        next_block = 0
        for states in states_by_block:
            groups: dict[tuple[tuple[int, Weight], ...], list[int]] = {}
            for state in states:
                groups.setdefault(_signature(row_list[state], partition), []).append(state)
            for signature in sorted(groups):
                for state in groups[signature]:
                    refined[state] = next_block
                next_block += 1

        if refined == partition:
            return partition
        partition = refined


def quotient(
    rows: Iterable[Mapping[object, object]], mapping: Iterable[object]
) -> list[Row]:
    """Return the exact quotient rows for an equitable ``mapping``.

    The output has one dictionary for each block, indexed by canonical block
    ID.  A ``ValueError`` is raised if ``mapping`` is not equitable, because a
    representative row would otherwise silently define an unsound quotient.
    Zero entries are omitted from the sparse output.
    """

    row_list = _validate_rows(rows)
    partition = _validate_mapping(mapping, len(row_list))
    block_count = len(set(partition))
    if block_count == 0:
        return []

    representatives = [-1] * block_count
    for state, block in enumerate(partition):
        if representatives[block] == -1:
            representatives[block] = state

    result: list[Row] = [
        _aggregate(row_list[representative], partition)
        for representative in representatives
    ]
    for state, row in enumerate(row_list):
        if _aggregate(row, partition) != result[partition[state]]:
            raise ValueError("mapping is not equitable for the supplied rows")
    return result


def verify_equitable(
    rows: Iterable[Mapping[object, object]],
    mapping: Iterable[object],
    quotient_rows: Iterable[Mapping[object, object]],
) -> bool:
    """Check ``AP=PB`` exactly, returning ``False`` for malformed inputs.

    ``quotient_rows`` is expected in the same sparse row format as ``rows``
    but indexed by block ID.  Explicit zero entries are accepted and treated
    as the same sparse row as an omitted zero.
    """

    try:
        row_list = _validate_rows(rows)
        partition = _validate_mapping(mapping, len(row_list))
        q_list = _validate_rows(quotient_rows)
        block_count = len(set(partition))
        if len(q_list) != block_count:
            return False
        expected = [
            _aggregate(q_list[block], list(range(block_count)))
            for block in range(block_count)
        ]
        # ``_validate_rows`` on quotient rows validates destinations against
        # block_count; the identity mapping above only canonicalizes zeros.
        for state, row in enumerate(row_list):
            if _aggregate(row, partition) != expected[partition[state]]:
                return False
        return True
    except Exception:
        return False


def lift_vector(mapping: Iterable[object], vector: Iterable[object]) -> list[Weight]:
    """Lift a quotient vector to states by copying its block value.

    For the block-incidence matrix ``P``, this returns ``P @ vector``.  Both
    integer and rational nonnegative entries are retained exactly.
    """

    mapping_list = _materialize(mapping, "mapping")
    partition = _validate_mapping(mapping_list, len(mapping_list))
    vector_list = _materialize(vector, "vector")
    block_count = len(set(partition))
    if len(vector_list) != block_count:
        raise ValueError(
            f"vector has length {len(vector_list)} but mapping has {block_count} blocks"
        )
    checked: list[Weight] = [
        _validate_weight(value, f"vector[{block}]")
        for block, value in enumerate(vector_list)
    ]
    return [checked[block] for block in partition]
